#!/bin/bash

#echo -e "|[ type ] 	            layout  |"

##################################################################################
#	Bomj PacKaGe tool ver 0.1
#  TODO: MAKE THIS SHIT
##################################################################################
# colors

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

finestr=''${GREEN}' fine '${NC}''
failstr=''${RED}' error '${NC}''
warnstr=''${YELLOW}' warn '${NC}''

##################################################################################
# bomj tools

exitdb() {
	rm -f /var/bpkg/lock
	exit 1
}

installcheck() {
	echo -e "|[${failstr}] 	     reinstall bpkg |"
	exit 0
}

searchfunc() {
	local -n searchinpkg=$1
	neededpkg=($(printf "%s\n" "${searchinpkg[@]}" | awk '!seen[$0]++'))
	grep -v '^&' /etc/bpkg.d/list | sed 's/ /\n/g' > /var/bpkg/temp/repos
	reposcount=$(wc -l /var/bpkg/temp/repos | cut -d ' ' -f 1)
	notfound=()
	i=1; while [ $i -le $reposcount ]; do	
		reponame=$(sed -n "${i}p" /var/bpkg/temp/repos | cut -d '|' -f 1)
		packagescount=$(cat /var/bpkg/db/$reponame/pkglist.json | jq '.packages | length')
		j=0; while [ $j -lt $packagescount ]; do
			foundedpkg=$(cat /var/bpkg/db/$reponame/pkglist.json | jq '.packages['$j'].name' | sed -e 's/"//g' )
			k=0; while [ $k -lt ${#neededpkg[@]} ]; do 
				if [ $foundedpkg == ${neededpkg[${k}]} ]; then
					searchfuncoutpath+=($(cat /var/bpkg/db/$reponame/pkglist.json | jq '.packages['$j'].path' | sed -e 's/"//g'; ))
					searchfuncoutname+=($(cat /var/bpkg/db/$reponame/pkglist.json | jq '.packages['$j'].name' | sed -e 's/"//g'; ))
					searchfuncoutver+=($(cat /var/bpkg/db/$reponame/pkglist.json | jq '.packages['$j'].version' | sed -e 's/"//g'; ))
				fi
				k=$((k + 1))
			done
			j=$((j + 1))
		done
		i=$((i + 1))
	done

	rm -f /var/bpkg/temp/repos
}
##################################################################################
# repo
sync() {
	source /etc/bpkg.d/func/sync

}

search() {
	source /etc/bpkg.d/func/search
}
# pkgs
update() {
	sync
	echo -e 'update'
}
purge() {
	touch /var/bpkg/lock > /dev/null
	echo -e 'purge'
}

localinstall() {
	source /etc/bpkg.d/func/localinstall
}

install() {
	touch /var/bpkg/lock > /dev/null

}

list() {
	touch /var/bpkg/lock > /dev/null
	echo -e 'list'
}
##################################################################################
# help
helpkg() {
	echo -e \
	 " |[ help ] -S --sync     | synchronize repo     |\n" \
	 "|[ help ] -D --delete   | delete pkgs          |\n" \
	 "|[ help ] -I --install  | install pkgs         |\n" \
	 "|[ help ] -L --list     | list installed pkgs  |\n" \
	 "|[ help ] -F --find     | find pkgs in repo    |\n" \
	 "|[ help ] -Li --local   | install pkg from bkg |\n" \
	 "|[ help ] -U --upgrade  | upgrade your system  |\n"
	exit 0 
}
versionpkg() {
	echo "======================================"
	echo -e "=   bpkg ver 0.1 '\033[0;36mBetta splendens\033[0m'  ="
	echo "======================================"
	exit 0 
}
input=("$@")

if [[ "$input" =~ ^(-h|--help)$ ]] ; then
	helpkg
elif [[ "$input" =~ ^(-v|--version)$ ]] ; then
	versionpkg
elif [[ "$input" =~ ^(--setup)$ ]] ; then
	source ./func/setup
fi

if [ -f /var/bpkg/lock ]; then
	echo -e "|[${failstr}] 	    lock file found |"
	exit 1
fi

if [ "$EUID" -ne 0 ]; then 
	
	echo -e "|[${failstr}] 	  permission denied |"
	exitdb
fi

if [ -f /bin/bpkg ] || [ -d /var/bpkg ] || [ -d /etc/bpkg ]; then
	echo -e "|[${finestr}] 	            started |"
else
	installcheck
fi

case ${input[0]} in
	'-S'|'--sync')
		sync
		exitdb
	;;
	'-D'|'--delete')
		purge
		exitdb
	;;
	'-I'|'--install')
		install
		exitdb
	;;
	'-L'|'--list')
		list
		exitdb
	;;
	'-F'|'--find')
		search
		exitdb
	;;
	'-U'|'--upgrade')
		update
		exitdb
	;;
	'-Li'|'--local')
		filetoinstall=${input[1]}
		localinstall
		exitdb
	;;
	'')
		echo -e "no operation specified"
	;;
	*)
		echo -e "|[${failstr}] 	     unknown option || $input |"
	;;
esac
