#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

install() {
    echo -e "${NC}####################|installing|####################${YELLOW}"
    echo -e "${GREEN}|| Thank you for installing bpkg... ||${YELLOW}"
	mkdir -v /var/bpkg
	mkdir -v /var/bpkg/repospkg /var/bpkg/db /var/bpkg/temp
	mkdir -v /etc/bpkg.d
	cp -rfv ./func /etc/bpkg.d/
    rm /etc/bpkg.d/setup
    echo "sys|https://github.com/Pelmeny/bpkg-repo|main" > /etc/bpkg.d/list
    cp ./bpkg /bin/
	echo -e "${NC}####################################################"
}
reinstall() {
    echo -e "#####################|removing|#####################${RED}"
    rm -rvf /var/bpkg /etc/bpkg* 
    install
}
echo -e "======================================"
echo -e "=   bpkg ver 0.2 '\033[0;36mBetta splendens\033[0m'  ="
echo -e "======================================"
response="0"
process="install"
if [ -f /bin/bpkg ] || [ -d /var/bpkg ] || [ -d /etc/bpkg ]; then
    process="reinstall"
fi
while [ $response = 0 ] ; do
    echo -e "Are you want to ${process} bpkg to your linux (${GREEN}Y${NC}/${RED}N${NC})"
    read -rp "?? " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        ${process}
    elif [[ "$response" =~ ^([nN][oO]|[nN])$ ]]; then
        exit 0
    else 
        response="0"
    fi
done

exit 0